# TCL File Generated by Component Editor 15.0
# Wed Mar 16 14:45:59 PDT 2016
# DO NOT MODIFY


#
# pmod_mic"pmod_mic" v1.0
#  2016.03.16.14:45:59
#
#

#
# request TCL package from ACDS 15.0
#
package require -exact qsys 15.0


#
# module pmod_mic
#
set_module_property DESCRIPTION ""
set_module_property NAME pmod_mic
set_module_property VERSION 1.0
set_module_property GROUP Vectorblox/Peripherals
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME pmod_mic
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pmod_mic_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pmod_mic_avalon.vhd VHDL PATH pmod_mic_avalon.vhd TOP_LEVEL_FILE
add_fileset_file pmod_mic_ref_comp.vhd VHDL PATH pmod_mic_ref_comp.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL pmod_mic_avalon
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pmod_mic_avalon.vhd VHDL PATH pmod_mic_avalon.vhd
add_fileset_file pmod_mic_ref_comp.vhd VHDL PATH pmod_mic_ref_comp.vhd


#
# parameters
#
add_parameter PORTS INTEGER 1
set_parameter_property PORTS DEFAULT_VALUE 1
set_parameter_property PORTS DISPLAY_NAME PORTS
set_parameter_property PORTS TYPE INTEGER
set_parameter_property PORTS UNITS None
set_parameter_property PORTS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PORTS HDL_PARAMETER true
add_parameter CLK_FREQ_HZ POSITIVE 25000000
set_parameter_property CLK_FREQ_HZ DEFAULT_VALUE 25000000
set_parameter_property CLK_FREQ_HZ DISPLAY_NAME CLK_FREQ_HZ
set_parameter_property CLK_FREQ_HZ TYPE POSITIVE
set_parameter_property CLK_FREQ_HZ UNITS None
set_parameter_property CLK_FREQ_HZ ALLOWED_RANGES 1:2147483647
set_parameter_property CLK_FREQ_HZ HDL_PARAMETER true
add_parameter SAMPLE_RATE_HZ POSITIVE 48000
set_parameter_property SAMPLE_RATE_HZ DEFAULT_VALUE 48000
set_parameter_property SAMPLE_RATE_HZ DISPLAY_NAME SAMPLE_RATE_HZ
set_parameter_property SAMPLE_RATE_HZ TYPE POSITIVE
set_parameter_property SAMPLE_RATE_HZ UNITS None
set_parameter_property SAMPLE_RATE_HZ ALLOWED_RANGES 1:2147483647
set_parameter_property SAMPLE_RATE_HZ HDL_PARAMETER true


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point conduit_end
#
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end sdata sdata Input ports
add_interface_port conduit_end sclk sclk Output ports
add_interface_port conduit_end cs_n cs_n Output ports


#
# connection point s1
#
add_interface s1 avalon end
set_interface_property s1 addressUnits SYMBOLS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 av_address address Input 8
add_interface_port s1 av_read read Input 1
add_interface_port s1 av_readdata readdata Output 32
add_interface_port s1 av_write write Input 1
add_interface_port s1 av_writedata writedata Input 32
add_interface_port s1 av_waitrequest waitrequest Output 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0
