# TCL File Generated by Component Editor 17.1
# Thu Mar 08 14:46:09 PST 2018
# DO NOT MODIFY


#
# orca_timer "ORCATimer" v1.0
# VectorBlox Computing Inc. 2018.03.08.14:46:09
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module orca_timer
#
set_module_property DESCRIPTION ""
set_module_property NAME orca_timer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "VectorBlox Computing Inc."
set_module_property AUTHOR "VectorBlox Computing Inc."
set_module_property DISPLAY_NAME "ORCA Timer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL orca_timer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file orca-timer.vhd VHDL PATH hdl/orca-timer.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL orca_timer
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file orca-timer.vhd VHDL PATH hdl/orca-timer.vhd


#
# parameters
#
add_parameter TIMER_WIDTH INTEGER 64 ""
set_parameter_property TIMER_WIDTH DEFAULT_VALUE 64
set_parameter_property TIMER_WIDTH DISPLAY_NAME "Timer Width"
set_parameter_property TIMER_WIDTH WIDTH ""
set_parameter_property TIMER_WIDTH TYPE INTEGER
set_parameter_property TIMER_WIDTH UNITS bits
set_parameter_property TIMER_WIDTH ALLOWED_RANGES {32 64}
set_parameter_property TIMER_WIDTH DESCRIPTION ""
set_parameter_property TIMER_WIDTH HDL_PARAMETER true


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point Timer_Interface
#
add_interface Timer_Interface conduit end
set_interface_property Timer_Interface associatedClock clock
set_interface_property Timer_Interface associatedReset ""
set_interface_property Timer_Interface ENABLED true
set_interface_property Timer_Interface EXPORT_OF ""
set_interface_property Timer_Interface PORT_NAME_MAP ""
set_interface_property Timer_Interface CMSIS_SVD_VARIABLES ""
set_interface_property Timer_Interface SVD_ADDRESS_GROUP ""

add_interface_port Timer_Interface timer_value value Output 64
add_interface_port Timer_Interface timer_interrupt interrupt Output 1


#
# connection point extra_signals
#
add_interface extra_signals conduit end
set_interface_property extra_signals associatedClock clock
set_interface_property extra_signals associatedReset ""
set_interface_property extra_signals ENABLED false
set_interface_property extra_signals EXPORT_OF ""
set_interface_property extra_signals PORT_NAME_MAP ""
set_interface_property extra_signals CMSIS_SVD_VARIABLES ""
set_interface_property extra_signals SVD_ADDRESS_GROUP ""

add_interface_port extra_signals slave_AWLOCK slave_awlock Input 2
add_interface_port extra_signals slave_ARCACHE slave_arcache Input 4
add_interface_port extra_signals slave_ARID slave_arid Input 4
add_interface_port extra_signals slave_ARLEN slave_arlen Input 4
add_interface_port extra_signals slave_ARLOCK slave_arlock Input 2
add_interface_port extra_signals slave_ARSIZE slave_arsize Input 3
add_interface_port extra_signals slave_ARBURST slave_awburst Input 2
add_interface_port extra_signals slave_AWBURST slave_awburst Input 2
add_interface_port extra_signals slave_AWCACHE slave_awcache Input 4
add_interface_port extra_signals slave_AWID slave_awid Input 4
add_interface_port extra_signals slave_AWLEN slave_awlen Input 4
add_interface_port extra_signals slave_AWSIZE slave_awsize Input 3
add_interface_port extra_signals slave_BID slave_bid Output 4
add_interface_port extra_signals slave_RID slave_rid Output 4
add_interface_port extra_signals slave_RLAST slave_rlast Output 1
add_interface_port extra_signals slave_WID slave_wid Input 4
add_interface_port extra_signals slave_WLAST slave_wlast Input 1


#
# connection point slave
#
add_interface slave axi4lite end
set_interface_property slave associatedClock clock
set_interface_property slave associatedReset reset
set_interface_property slave readAcceptanceCapability 1
set_interface_property slave writeAcceptanceCapability 1
set_interface_property slave combinedAcceptanceCapability 1
set_interface_property slave readDataReorderingDepth 1
set_interface_property slave bridgesToMaster ""
set_interface_property slave ENABLED true
set_interface_property slave EXPORT_OF ""
set_interface_property slave PORT_NAME_MAP ""
set_interface_property slave CMSIS_SVD_VARIABLES ""
set_interface_property slave SVD_ADDRESS_GROUP ""

add_interface_port slave slave_ARADDR araddr Input 4
add_interface_port slave slave_ARPROT arprot Input 3
add_interface_port slave slave_ARVALID arvalid Input 1
add_interface_port slave slave_ARREADY arready Output 1
add_interface_port slave slave_RDATA rdata Output 32
add_interface_port slave slave_RVALID rvalid Output 1
add_interface_port slave slave_RREADY rready Input 1
add_interface_port slave slave_AWADDR awaddr Input 4
add_interface_port slave slave_AWPROT awprot Input 3
add_interface_port slave slave_AWVALID awvalid Input 1
add_interface_port slave slave_AWREADY awready Output 1
add_interface_port slave slave_WDATA wdata Input 32
add_interface_port slave slave_WSTRB wstrb Input 4
add_interface_port slave slave_WVALID wvalid Input 1
add_interface_port slave slave_WREADY wready Output 1
add_interface_port slave slave_BVALID bvalid Output 1
add_interface_port slave slave_BREADY bready Input 1
add_interface_port slave slave_BRESP bresp Output 2
add_interface_port slave slave_RRESP rresp Output 2
