#ifndef __BSP_H
#define __BSP_H
#include "orca_defines.h"
#define ORCA_CLK 100000000

#define PS7_UART_BASE_ADDRESS  ORCA_DUC_PS7_UART_1_BASE_ADDR

#define AXI_TIMER_BASE_ADDRESS    ORCA_DUC_AXI_TIMER_BASE_ADD
#define AXI_GPIO_LEDS_BASE_ADDRESS ORCA_DUC_AXI_GPIO_LEDS_BASE_ADDR

//#define ORCA_ENABLE_EXCEPTIONS
//#define ORCA_ENABLE_EXT_INTERRUPTS 1
//#define ORCA_NUM_EXT_INTERRUPTS    2

#define AXI_TIMER_CLK 100000000

#endif //#ifndef __BSP_H
